# Generated by Django 4.2.7 on 2023-11-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('data_admissao', models.DateField()),
                ('funcao', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
